In [22]:
import tensorflow as tf
import pickle

In [23]:
loaded_model = tf.keras.models.load_model('./DL_tech.h5')
loaded_model

In [24]:
# !python -m pip install konlpy

In [30]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))

In [31]:
import konlpy

In [32]:
okt = konlpy.tag.Okt()

In [33]:
new_sentence = okt.morphs('정말 추천해요', stem=True)

In [34]:
new_sentence = [tok for tok in new_sentence if tok not in stopwords]

In [35]:
new_sentence

['정말', '추천']

In [37]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

In [38]:
vocab_size = len(tokenizer.word_index)
vocab_size

4419

# padding

In [39]:
encoded = tokenizer.texts_to_sequences([new_sentence])

In [40]:
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=200)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

# predict

In [41]:
score = loaded_model.predict(pad_new)
score

array([[0.06908475, 0.20519106, 0.20491867, 0.50973153, 0.01107406]],
      dtype=float32)

# Service

In [42]:
def sentiment_predict(sentence):
  okt=konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [tok for tok in new_sentence if tok not in stopwords]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [43]:
words = '완전 별로에요 후회합니다'
sentiment_predict(words)

array([[8.5770595e-01, 9.8703586e-06, 1.6440961e-05, 1.1683453e-03,
        1.4109927e-01]], dtype=float32)