In [19]:
import tensorflow as tf

In [20]:
loaded_model = tf.keras.models.load_model('./DL_culture.h5')
loaded_model

In [21]:
# !python -m pip install konlpy

In [27]:
import konlpy

In [28]:
okt = konlpy.tag.Okt()

In [29]:
new_sentence = okt.morphs('정말 추천해요', stem=True)

In [30]:
new_sentence = [tok for tok in new_sentence if tok not in stopwords]

In [31]:
new_sentence

['정말', '추천']

In [33]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

In [34]:
vocab_size = len(tokenizer.word_index)
vocab_size

4419

# padding

In [35]:
encoded = tokenizer.texts_to_sequences([new_sentence])

In [36]:
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=200)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

# predict

In [38]:
score = loaded_model.predict(pad_new)
score

array([[0.0316682 , 0.00884722, 0.04516983, 0.1422723 , 0.77204245]],
      dtype=float32)

# Service

In [39]:
def sentiment_predict(sentence):
  okt=konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [tok for tok in new_sentence if tok not in stopwords]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [41]:
words = '완전 별로에요 후회합니다'
sentiment_predict(words)

array([[0.04963229, 0.01520427, 0.05801909, 0.19837768, 0.6787666 ]],
      dtype=float32)