In [2]:
import tensorflow as tf
import pickle

In [3]:
loaded_model = tf.keras.models.load_model('./DL_tech.h5')
loaded_model

In [4]:
# !python -m pip install konlpy

     |████████████████████████████████| 19.4 MB 1.3 MB/s 
     |████████████████████████████████| 448 kB 41.3 MB/s 
     |████████████████████████████████| 86 kB 4.2 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [5]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))

In [6]:
import konlpy

In [7]:
okt = konlpy.tag.Okt()

In [8]:
# input_sentence = input('예상 리뷰를 입력하세요.')

In [9]:
new_sentence = okt.morphs('정말 추천해요', stem=True)

In [10]:
new_sentence = [tok for tok in new_sentence if tok not in stopwords]

In [11]:
new_sentence

['정말', '추천']

In [12]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

In [13]:
vocab_size = len(tokenizer.word_index)
vocab_size

4419

# padding

In [14]:
encoded = tokenizer.texts_to_sequences([new_sentence])

In [15]:
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=200)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

# predict

In [16]:
score = loaded_model.predict(pad_new)
score

array([[0.06908475, 0.20519106, 0.20491867, 0.50973153, 0.01107406]],
      dtype=float32)

# Service

In [17]:
def sentiment_predict(sentence):
  okt=konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [tok for tok in new_sentence if tok not in stopwords]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [21]:
words = input('리뷰를 입력하세요.')
result = sentiment_predict(words)

리뷰를 입력하세요.완전 구려요


In [28]:
result

array([[0.00875925, 0.02128283, 0.6954595 , 0.25938386, 0.01511457]],
      dtype=float32)

# 시각화 자료

In [46]:
negative = (result[0][0]+result[0][1]+result[0][2])*100
positive = (result[0][3]+result[0][4])*100

In [59]:
negative, positive

(72.55015969276428, 27.449843287467957)

In [60]:
list = [negative, positive]

In [69]:
import plotly.express as px

fig = px.pie(list, values= list, names=list, color=list,
             color_discrete_map={negative :'lightslategray',
                                 positive :'royalblue'})

fig.show()